# Generated by Django 5.2.11 on 2026-04-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0013_normalize_rates_to_rate_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costmodel",
            name="rates",
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION process_cost_model_audit() RETURNS TRIGGER AS $cost_model_audit$
                DECLARE
                    provider_uuids uuid[];
                BEGIN
                    IF (TG_OP = 'DELETE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = OLD.uuid);
                        INSERT INTO cost_model_audit (id, operation, audit_timestamp, provider_uuids,
                            uuid, name, description, source_type, created_timestamp, updated_timestamp,
                            rates, markup, distribution, distribution_info, currency)
                        VALUES (nextval('cost_model_audit_id_seq'), 'DELETE', now(), provider_uuids,
                            OLD.uuid, OLD.name, OLD.description, OLD.source_type, OLD.created_timestamp, OLD.updated_timestamp,
                            '{}'::jsonb, OLD.markup, OLD.distribution, OLD.distribution_info, OLD.currency);
                        RETURN OLD;
                    ELSIF (TG_OP = 'UPDATE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit (id, operation, audit_timestamp, provider_uuids,
                            uuid, name, description, source_type, created_timestamp, updated_timestamp,
                            rates, markup, distribution, distribution_info, currency)
                        VALUES (nextval('cost_model_audit_id_seq'), 'UPDATE', now(), provider_uuids,
                            NEW.uuid, NEW.name, NEW.description, NEW.source_type, NEW.created_timestamp, NEW.updated_timestamp,
                            '{}'::jsonb, NEW.markup, NEW.distribution, NEW.distribution_info, NEW.currency);
                        RETURN NEW;
                    ELSIF (TG_OP = 'INSERT') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit (id, operation, audit_timestamp, provider_uuids,
                            uuid, name, description, source_type, created_timestamp, updated_timestamp,
                            rates, markup, distribution, distribution_info, currency)
                        VALUES (nextval('cost_model_audit_id_seq'), 'INSERT', now(), provider_uuids,
                            NEW.uuid, NEW.name, NEW.description, NEW.source_type, NEW.created_timestamp, NEW.updated_timestamp,
                            '{}'::jsonb, NEW.markup, NEW.distribution, NEW.distribution_info, NEW.currency);
                        RETURN NEW;
                    END IF;
                    RETURN NULL;
                END;
            $cost_model_audit$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION process_cost_model_audit() RETURNS TRIGGER AS $cost_model_audit$
                DECLARE
                    provider_uuids uuid[];
                BEGIN
                    IF (TG_OP = 'DELETE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = OLD.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'DELETE', now(), provider_uuids, OLD.*;
                        RETURN OLD;
                    ELSIF (TG_OP = 'UPDATE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'UPDATE', now(), provider_uuids, NEW.*;
                        RETURN NEW;
                    ELSIF (TG_OP = 'INSERT') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'INSERT', now(), provider_uuids, NEW.*;
                        RETURN NEW;
                    END IF;
                    RETURN NULL;
                END;
            $cost_model_audit$ LANGUAGE plpgsql;
            """,
        ),
    ]
