# Generated by Django 5.2.11 on 2026-04-09 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0016_update_audit_trigger"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="costmodelaudit",
                    name="cost_model_context",
                    field=models.CharField(max_length=50, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="costmodelcontext",
            name="position",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
